---
apiVersion: v1
kind: Namespace
metadata:
  name: docs-dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hippius-docs-dev
  namespace: docs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hippius-docs-dev
  template:
    metadata:
      labels:
        app: hippius-docs-dev
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: hippius-docs-dev
          image: ${IMAGE}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: hippius-docs-dev
  namespace: docs-dev
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: hippius-docs-dev

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hippius-docs-dev
  namespace: docs-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - docs-dev.hippicode.com
      secretName: hippius-docs-dev-tls
  rules:
    - host: docs-dev.hippicode.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hippius-docs-dev
                port:
                  number: 80
