---
apiVersion: v1
kind: Namespace
metadata:
  name: docs-dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hippius-docs-dev
  namespace: docs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hippius-docs-dev
  template:
    metadata:
      labels:
        app: hippius-docs-dev
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: hippius-docs-dev
          image: ${IMAGE}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: hippius-docs-dev
  namespace: docs-dev
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: hippius-docs-dev

